<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Ultimate Loot Editor</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(GameRoot)SPT_Runtime\user\mods\Ultimate Loot Editor\</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\UltimateLootEditor.Shared\ModConstants.cs" Link="ModConstants.cs" />
    <Compile Include="..\UltimateLootEditor.Shared\MapCatalog.cs" Link="MapCatalog.cs" />
    <Compile Include="..\UltimateLootEditor.Shared\UleSchema.cs" Link="UleSchema.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(GameRoot)SPT_Runtime\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>$(GameRoot)SPT_Runtime\SemanticVersioning.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Common">
      <HintPath>$(GameRoot)SPT_Runtime\SPTarkov.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.DI">
      <HintPath>$(GameRoot)SPT_Runtime\SPTarkov.DI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Reflection">
      <HintPath>$(GameRoot)SPT_Runtime\SPTarkov.Reflection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>$(GameRoot)SPT_Runtime\SPTarkov.Server.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
